config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root "static_pages#home"

  resources :reviews do
    resources :comments
  end
  resources :train_texts
  resources :searches
  resources :users
  resources :clipped_reviews, controller: "clipped_reviews"

  namespace :admin do
    root "static_pages#home"
    resources :trains
    resources :train_texts
    resources :train_reviews
    resources :test_reviews
    resources :reviews
    resources :users
  end
end

app/controllers/admin/train_reviews_controller.rb
class Admin::TrainReviewsController < Admin::AdminController
  def index
    @train_reviews=TrainReview.page params[:page]
  end

  def new
    @train_review=TrainReview.new
    @reviews=Review.untrained.page params[:page]
  end

  def create
    begin
      @train_review=TrainReview.create train_review_params
      @train_text=TrainText.find(train_review_params[:_id])
      unless @train_text.nil?
        @train_text.delete
        redirect_to admin_train_reviews_path
      else
        redirect_to new_admin_train_review_path
      end
    rescue  => e
      flash[:danger] = e
      @train_review=TrainReview.find(train_review_params[:_id])
      redirect_to edit_admin_train_review_path(@train_review)
    end
  end

  def show
    @train_review=TrainReview.find(params[:id])
    @review=Review.find(params[:id])
  end

  def edit
    @review=Review.find(params[:id])
    @train_review=TrainReview.find(params[:id])
  end

  def update
    @train_review=TrainReview.find params[:id]
    @train_review.update_attributes train_review_params
    redirect_to [:admin,@train_review]
    flash[:sucess]= "Train data has been updated"
  end

  def destroy
    TrainReview.find(params[:id]).destroy
    redirect_to admin_train_reviews_path
    flash[:sucess]= "Train review has been deleted"
  end

  private
  def train_review_params
    params.require(:train_review).permit(:_id,:review,:category)
  end
end

app/views/admin/train_reviews/_train_review.html.erb
<tr>
  <td>
    <%= Review.find(train_review.id).review[0..400] %>...
  </td>
  <td>
     <span class="ui <%=type_label_color(train_review.category)%> basic label">
      <%= train_review.category.capitalize%>
    </span>
  </td>
  <td>
    <%= link_to [:admin,train_review] do %>
     <div class="ui small green button active"><i class="info icon"></i></div>
    <% end%>
    <%= link_to [:admin,train_review], method: :delete, data:{confirmation: "Are you sure?"} do %>
     <div class="ui small red button active"><i class="trash icon"></i></div>
    <% end%>
  </td>
</tr>

app/views/admin/train_reviews/edit.html.erb
<%provide(:title, "Train review edit")%>
<div class="ui huge breadcrumb">
 <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_test_reviews_path%>">Test reviews</a>
  <i class="right chevron icon divider"></i>
  <div class="active section">Edit: <a href="<%=admin_train_review_path(@train_review)%>"><%=@review.title[0..20]%>...</a></div>
</div>

<div class="ui big red message">
  <p class="big red">You have to change the train review</p>
</div>
<div id="container">
  <h1 class="ui header"><%= @review.title %></h1>
  <div class="ui message page grid">
        <p> Posted at <%= @review.published_date.strftime("%d/%m/%Y")%> @ <%=link_to "#{@review.host}",reviews_path(forum: "#{@review.host}")%>.<br>
        This review has been viewed <%= @review.popular%> times and classified into
        <%= render 'shared/review_category_tag'%>
           category by <%=link_to "SocialReader", root_path%>.<br>
        You can also view <%= link_to "source review", @review.url%>.</p>
          <div class="row">
          <div class="eight wide column">
          <div class="field">
            <label>This review was trainned by admin as:</label>
          </div>
          <div class="field">
              <span class="ui <%=type_label_color(@train_review.category)%> basic label">
                <%= @train_review.category.capitalize%>
              </span>
          </div>
          </div>
          <div class="eight wide column">
           <div class="ui form">
            <%= form_for [:admin,@train_review] do |f|%>
            Do you want to change it?
            <%= f.hidden_field :review, value: @review.review%>
          <%= f.hidden_field :_id, value: @review.id%>
            <%= f.select(:category,Review::CATEGORIES-[@train_review.category], class: "ui dropdown")%>
            <%=f.submit "Update", class: "ui green button"%>
          <%end%>
            </div>
            <div class="row">
            Train data added @ <%=@train_review.created_at.strftime("%d/%m/%Y")%>
            <div class="eight wide column">
          <%= link_to "Delete", admin_train_review_path, method: :delete, data:{confirmation: "Are you sure?"}, class: "ui red button"%>
            </div>
          </div>
            </div>
          </div>
          </div>
  </div>
  <p><%=@review.content.html_safe%></p>
  <span class="ui tag label">Tags</span>
  <div class="ui celled horizontal list">
    <% @review.tag.each do |tag|%>
      <div class="item"><%=link_to "#{tag}", reviews_path(:tag=> tag)%></div>
    <% end %>
  </div>
</div>

app/views/admin/train_reviews/index.html.erb
<% provide(:title,"Train data")%>
<div class="ui huge breadcrumb">
  <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_train_reviews_path%>">Train reviews</a>
  <a href="<%=new_admin_train_review_path%>" class="ui green button">New train reviews</a>
</div>
<% if @train_reviews.any?%>

<div class="ui top attached tabular menu">
  <a class="item " data-tab="first">Statistic</a>
  <a class="item active" data-tab="second">Index</a>
</div>
<div class="ui bottom attached tab segment " data-tab="first">
  <table class="ui versy basic collapsing celled table">
    <thead>
      <tr>
        <th>Category</th>
        <th>Number of reviews</th>
      </tr>
    </thead>
    <tbody>
      <%Review::CATEGORIES.each do |cat|%>
      <tr>
          <td>
            <span class="ui <%=type_label_color(cat)%> basic label">
      <%= cat.capitalize%>
    </span>
          </td>
          <td>
            <%=@train_reviews.by_category(cat).count%>
          </td>
      </tr>
      <%end%>
    </tbody>
      <tfoot>
        <tr>
          <th>Total</th>
          <th><%=@train_reviews.count%></th>
        </tr>
      </tfoot>
  </table>
</div>
<div class="ui bottom attached tab segment active" data-tab="second">
  <table class="ui very basic collapsing celled table">
    <thead>
      <tr>
        <th>Review</th>
        <th>Category</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <div class="ui right aligned grid">
        <div class="left floated left aligned six wide column">
          <div class="ui segment">
            <%= paginate @train_reviews %>
          </div>
        </div>
        <div class="right floated right aligned six wide column">
          <div class="ui segment">
            <a class="ui left aligned green button" href="<%= new_admin_train_review_path %>"> New training data </a>
          </div>
        </div>
      </div>
      <%= render @train_reviews%>
    </tbody>
  </table>
</div>
<% else %>
  <div class="ui message">
    There is no train reviews
  </div>
<% end %>

app/views/admin/train_reviews/new.html.erb
<%provide(:title, "New train data")%>
<div class="ui huge breadcrumb">
 <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=new_admin_train_review_path%>">New training data</a>
</div>

<div>
  <%= paginate @reviews %>
  <%= render @reviews %>
  <%= paginate @reviews %>
</div>

app/views/admin/train_reviews/show.html.erb
<%provide(:title,"Train review")%>
<div class="ui huge breadcrumb">
 <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_train_reviews_path%>">Train reviews</a>
  <i class="right chevron icon divider"></i>
  <div class="active section">Train review: <a href="<%=admin_train_review_path(@train_review)%>"><%=@review.title[0..20]%>...</a></div>
</div>

<div id="container">
  <h1 class="ui header"><%= @review.title %></h1>
  <div class="ui message page grid" >
        <p> Posted at <%= @review.published_date.strftime("%d/%m/%Y")%> @ <%=link_to "#{@review.host}",reviews_path(forum: "#{@review.host}")%>.<br>
        This review has been viewed <%= @review.popular%> times and classified into
        <%=render 'shared/review_category_tag'%>
          category by <%=link_to "SocialReader", root_path%>.<br>
        You can also view <%= link_to "source review", @review.url%>.</p>
          <div class="row">
          <div class="eight wide column">
          <div class="field">
            <label>This review has been re-trained by admin as:</label>
          </div>
          <div class="field">
              <span class="ui <%=type_label_color(@train_review.category)%> basic label">
                <%= @train_review.category.capitalize%>
              </span>
          </div>
          </div>
          <div class="eight wide column">
            <div class="row">
            Train data added @ <%=@train_review.created_at.strftime("%d/%m/%Y")%>
            <div class="eight wide column">
          <%= link_to "Delete", admin_train_review_path, method: :delete, data:{confirmation: "Are you sure?"}, class: "ui red button"%>
            </div>
          </div>
            </div>
          </div>
          </div>
  <p><%=@review.content.html_safe%></p>
  <span class="ui tag label">Tags</span>
  <div class="ui celled horizontal list">
    <% @review.tag.each do |tag|%>
      <div class="item"><%=link_to "#{tag}", reviews_path(:tag=> tag)%></div>
    <% end %>
  </div>
</div>