config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root "static_pages#home"

  resources :reviews do
    resources :comments
  end
  resources :train_texts
  resources :searches
  resources :users
  resources :clipped_reviews, controller: "clipped_reviews"

  namespace :admin do
    root "static_pages#home"
    resources :trains
    resources :train_texts
    resources :train_reviews
    resources :test_reviews
    resources :reviews
    resources :users
  end
end

app/models/train_text.rb
class TrainText
  include Mongoid::Document

  field :_id, type: String
  field :category, type: Array
  validates :review_id, uniqueness: true

  belongs_to :review
  default_scope -> { order_by(:created_at => 'desc') }
  scope :unchecked, ->{where(checked: false)}

  class << self
    def new_text params
      review=Review.find(params[:review_id])
      train_text=review.train_text
      unless train_text
      review.create_train_text(category:[params[:category]])
      else
        categories=train_text.category << params[:category]
        train_text.category= categories
        byebug
      end
    end
  end

end

app/controllers/admin/train_texts_controller.rb
class Admin::TrainTextsController < Admin::AdminController
  def index
    @train_texts=TrainText.all
  end

  def show
    @train_text=TrainText.find params[:id]
    @review=Review.find params[:id]
  end

  def destroy
    @train_text=TrainText.find params[:id]
    @train_text.destroy
    flash[:sucess]="The train text has been deleted"
    redirect_to admin_train_texts_path
  end
end

app/controllers/train_texts_controller.rb
class TrainTextsController < ApplicationController
  def create
    review=Review.find(params[:train_text][:review_id])
    review.create_train_text train_text_params
    # train_text=TrainText.new_text train_text_params
    redirect_to review
    flash[:success]= "Thanks for your contribution"
  end

  private
  def train_text_params
    params[:train_text][:category]=[params[:train_text][:category]]
    params.require(:train_text).permit(:review_id,:category => [])
  end
end

app/views/admin/train_texts/_train_text.html.erb
<tr>
  <td>
    <%= Review.find(train_text.id).review[0..400] %>...

  </td>
  <td>
    <% train_text.category.each do |cat|%>
     <span class="ui <%=type_label_color(cat)%> basic label">
      <%= cat.capitalize%>
    </span>
     <%end %>
  </td>
  <td>
    <%= link_to [:admin,train_text] do %>
     <div class="ui small green button active"><i class="info icon"></i></div>
    <% end%>
    <%= link_to [:admin,train_text], method: :delete, data:{confirmation: "Are you sure?"} do %>
     <div class="ui small red button active"><i class="trash icon"></i></div>
    <% end%>
  </td>
</tr>

app/views/admin/train_texts/index.html.erb
<% provide(:title,"Train texts")%>
<div class="ui huge breadcrumb">
  <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_train_texts_path%>">Train texts</a>
</div>

<% if @train_texts.any?%>
  <table class="ui very basic collapsing celled table">
    <thead>
      <tr>
        <th>Review</th>
        <th>Re-classify</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render @train_texts%>
    </tbody>
  </table>
<% else %>
  <div class="ui message">
    There is no unchecked train texts from users
  </div>
<% end %>

app/views/admin/train_texts/show.html.erb
<%provide(:title,"Train text")%>

<div id="container">
  <h1 class="ui header"><%= @review.title %></h1>
  <div class="ui message page grid">
        <p> Posted at <%= @review.published_date.strftime("%d/%m/%Y")%> @ <%=link_to "#{@review.host}",reviews_path(forum: "#{@review.host}")%>.<br>
        This review has been viewed <%= @review.popular%> times and classified into
        <%= render 'shared/review_category_tag'%>   category by <%=link_to "SocialReader", root_path%>.<br>
        You can also view <%= link_to "source review", @review.url%>.</p>
          <div class="row">
          <div class="eight wide column">
          <div class="field">
            <label>This review is re-classified by user:</label>
          </div>
          <div class="field">
            <% @train_text.category.each do |cat| %>
              <span class="ui <%=type_label_color(cat)%> basic label">
                <%= cat.capitalize%>
              </span>
            <% end %>
          </div>
          </div>
          <div class="eight wide column">
            <div class="row">
            <div class="eight wide column">
              Check the train text?
          <div class="ui form">
            <%= form_for [:admin,TrainReview.new] do |f|%>
          <%= f.hidden_field :_id, value: @review.id%>
            <%= f.select(:category,Review::CATEGORIES, class: "ui dropdown")%>
            <%=f.submit "Add to train data", class: "ui green button"%>
          <%end%>
            </div>
            <div class="ui form">
            <%= form_for [:admin,TestReview.new] do |f|%>
          <%= f.hidden_field :_id, value: @review.id%>
            <%= f.select(:category,Review::CATEGORIES, class: "ui dropdown")%>
            <%=f.submit "Add to test data", class: "ui blue button"%>
          <%end%>
            </div>
          </div>
            <div class="eight wide column">
          <%= link_to "Delete", admin_train_text_path, method: :delete, data:{confirmation: "Are you sure?"}, class: "ui red button"%>
            </div>
          </div>
            </div>
          </div>
          </div>
  </div>
  <p><%=@review.content.html_safe%></p>
  <span class="ui tag label">Tags</span>
  <div class="ui celled horizontal list">
    <% @review.tag.each do |tag|%>
      <div class="item"><%=link_to "#{tag}", reviews_path(:tag=> tag)%></div>
    <% end %>
  </div>
</div>