config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root "static_pages#home"

  resources :reviews do
    resources :comments
  end
  resources :train_texts
  resources :searches
  resources :users
  resources :clipped_reviews, controller: "clipped_reviews"

  namespace :admin do
    root "static_pages#home"
    resources :trains
    resources :train_texts
    resources :train_reviews
    resources :test_reviews
    resources :reviews
    resources :users
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::AdminController
  def index
    @reviews=Review.with_params(params).page params[:page]
  end

  def edit
    @review=Review.find params[:id]
  end

  def update
    @review=Review.find params[:id]
    params[:review][:review]=Nokogiri::HTML(params[:review][:content]).text
    params[:review][:tag]=params[:review][:tag].split(",").to_a
    @review.update_attributes review_params
    redirect_to [:admin,@review]
    flash[:success] = "Review has been updated"
  end

  def show
    @review=Review.find(params[:id])
    @comment= @review.comments.build
  end

  def destroy
    @review=Review.find params[:id]
    @review.destroy
    flash[:success] = "Review has been deleted"
    redirect_to admin_reviews_path
  end

  def new
    @review=current_user.reviews.build
  end

  def create
    params[:review][:tag]=params[:review][:tag].split(",").to_a
    params[:review][:review]=Nokogiri::HTML(params[:review][:content]).text
    current_user.reviews.create! review_params
    redirect_to admin_reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:title, :host, :category, :published_date, :popular, :content, :review, :tag => [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
   @reviews=Review.with_params(params).page params[:page]
  end

  def show
      @review=Review.find(params[:id])
      @comment=@review.comments.build
      @train_text=TrainText.new
    if params[:clip]
      current_user.clipped_reviews << params[:clip] unless current_user.clipped_reviews.include? params[:clip]
      current_user.save
    elsif params[:unclip]
      current_user.clipped_reviews.delete(params[:unclip])
      current_user.save
    end
  end

  def new
    @review=current_user.reviews.build
  end

  def create
    params[:review][:tag]=params[:review][:tag].split(",").to_a
    params[:review][:review]=Nokogiri::HTML(params[:review][:content]).text
    current_user.reviews.create! review_params
    redirect_to reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:title, :host, :category, :published_date, :popular, :content, :review, :tag => [])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/_review.html.erb
<div class="ui items internally celled grid" style="padding-top:20px">
  <a class="ui large <%=type_label_color(review.category)%> ribbon label" href="/reviews?category=<%=review.category%>">
    <%=review.category.upcase%></a>
      <div class="raised item">
    <div class="ui internally celled grid">
   <div class="row">
     <div class="thirteen wide column">

      <a class="header" href="<%= admin_review_path(review)%>"><%=review.title%></a>
      <div class="fb-like" data-href="https://localhost:3000" data-layout="button" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
       <div class="meta">
      </div>
      <div class="description">
        <span><%=review.review[0..400]%></span>
      </div>
      <div class="extra">
      <span class="ui tag label">Tags</span>
        <div class="ui celled horizontal list">
          <% unless review.tag.nil?%>
          <%=review.tag.each do |tag|%>
            <div class="item"><%=link_to "#{tag}", reviews_path(:tag=> tag)%></div>
          <% end %>
          <%end%>
        </div>
        </div>
        <div class="ui bottom right attached label">
      <%=link_to "#{review.host}", reviews_path(forum: "#{review.host}")%></div>
        </div>
        <div class="three wide column">
          <div class="ui form">
             <%= form_for [:admin,TrainReview.new] do |f|%>
            <%= f.hidden_field :_id, value: review.id%>
              <%= f.select(:category,Review::CATEGORIES, class: "ui dropdown")%>
              <%=f.submit "Add to train data", class: "ui green button"%>
            <%end%>
          </div>
          <div class="ui form">
             <%= form_for [:admin,TestReview.new] do |f|%>
            <%= f.hidden_field :_id, value: review.id%>
              <%= f.select(:category,Review::CATEGORIES, class: "ui dropdown")%>
              <%=f.submit "Add to test data", class: "ui red button"%>
            <%end%>
          </div>
        </div>


    </div>
    </div>
  </div>
</div>

app/views/admin/reviews/_review2.html.erb
<div class="ui items internally celled grid" style="padding-top:20px">
  <a class="ui large <%=type_label_color(review.category)%> ribbon label" href="/reviews?category=<%=review.category%>">
    <%=review.category.upcase%></a>
      <div class="raised item">
    <div class="ui internally celled grid">
   <div class="row">
     <div class="thirteen wide column">

      <a class="header" href="<%= admin_review_path(review)%>"><%=review.title%></a>
      <div class="fb-like" data-href="https://localhost:3000" data-layout="button" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
       <div class="meta">
      </div>
      <div class="description">
        <span><%=review.review%></span>
      </div>
      <div class="extra">
      <span class="ui tag label">Tags</span>
        <div class="ui celled horizontal list">
          <% unless review.tag.nil?%>
          <%=review.tag.each do |tag|%>
            <div class="item"><%=link_to "#{tag}", reviews_path(:tag=> tag)%></div>
          <% end %>
          <%end%>
        </div>
        </div>
        <div class="ui bottom right attached label">
      <%=link_to "#{review.host}", reviews_path(forum: "#{review.host}")%></div>
        </div>
        <div class="three wide column">
          <div class="ui form">
             <%= form_for [:admin,TrainReview.new] do |f|%>
            <%= f.hidden_field :_id, value: review.id%>
              <%= f.select(:category,Review::CATEGORIES, class: "ui dropdown")%>
              <%=f.submit "Add to train data", class: "ui green button"%>
            <%end%>
          </div>
          <div class="ui form">
             <%= form_for [:admin,TestReview.new] do |f|%>
            <%= f.hidden_field :_id, value: review.id%>
              <%= f.select(:category,Review::CATEGORIES, class: "ui dropdown")%>
              <%=f.submit "Add to test data", class: "ui red button"%>
            <%end%>
          </div>
        </div>


    </div>
    </div>
  </div>
</div>

app/views/admin/reviews/edit.html.erb
<%provide(:title,"Edit review")%>
<div class="ui huge breadcrumb">
  <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_reviews_path%>">Reviews</a>
  <i class="right chevron icon divider"></i>
  <div class="active section">Edit: <a href="<%=admin_review_path(@review)%>"><%=@review.title[0..20]%>...</a></div>
</div>
<br>
<%= form_for [:admin,@review] do |f|%>
<div class="ui form">
  <h4 class="ui dividing header">Information</h4>
  <div class="field">
    <label>Title</label>
      <div class="field">
        <%= f.text_field :title, placeholder: "Title"%>
      </div>
  </div>
  <div class="two fields">
    <div class="field">
      <label>Category</label>
       <%= f.select(:category,Review::CATEGORIES,:multiple => true, class: "ui dropdown")  %>
    </div>
  </div>
  <h4 class="ui dividing header">Content</h4>
  <%= f.cktext_area :content %>
  <div class="field">
    <label>Tag</label>
      <div class="field">
        <%= f.text_field :tag, placeholder: "Divided by ,"%>
      </div>
  </div>
  <%= f.submit "Submit", class: "positive ui button"%>
<%end%>

app/views/admin/reviews/index.html.erb
<%provide(:title,"Reviews")%>
<div class="ui huge breadcrumb">
  <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_reviews_path%>">Reviews</a>
  <a href="<%=new_admin_review_path%>" class="ui green button">New review</a>
</div>
<% if @reviews.any?%>
<div class="ui top attached tabular menu">
  <a class="item " data-tab="first">Statistic</a>
  <a class="item active" data-tab="second">Index</a>
</div>
<div class="ui bottom attached tab segment " data-tab="first">
  <table class="ui versy basic collapsing celled table">
    <thead>
      <tr>
        <th>Category</th>
        <th>Number of reviews</th>
      </tr>
    </thead>
    <tbody>
      <%Review::CATEGORIES.each do |cat|%>
      <tr>
          <td>
            <span class="ui <%=type_label_color(cat)%> basic label">
      <%= cat.capitalize%>
    </span>
          </td>
          <td>
            <%=@reviews.by_category(cat).count%>
          </td>
      </tr>
      <%end%>
    </tbody>
      <tfoot>
        <tr>
          <th>Total</th>
          <th><%=@reviews.count%></th>
        </tr>
      </tfoot>
  </table>
</div>
<div class="ui bottom attached tab segment active" data-tab="second">
<%Review::CATEGORIES.each do |cat|%>
  <% unless params[:search]%>
    <a class="ui <%=type_label_color(cat)%> button" href="<%=admin_reviews_path(category: "#{cat}")%>"><%=cat.upcase%></a>
  <%else%>
    <a class="ui <%=type_label_color(cat)%> button" href="<%=admin_reviews_path(search: "#{params[:search]}",category: "#{cat}")%>"><%=cat.upcase%></a>
  <%end%>
<% end %>
  <%= paginate(@reviews) %>
<%= render @reviews%>
  <%= paginate(@reviews) %>
</div>
<% else %>
  <div class="ui bottom attached tab segment active">
    No result has the term "<%=params[:search]%>". Go to <%= link_to "Advanced search", new_search_path%> for more informations
  </div>
<% end %>

app/views/admin/reviews/new.html.erb
<%provide(:title,"New review")%>
<div class="ui huge breadcrumb">
  <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_reviews_path%>">Reviews</a>
  <i class="right chevron icon divider"></i>
  <div class="active section">New review</div>
</div>
<%= form_for [:admin,@review] do |f|%>
<div class="ui form">
  <h4 class="ui dividing header">Information</h4>
  <div class="field">
    <label>Title</label>
      <div class="field">
        <%= f.text_field :title, placeholder: "Title"%>
      </div>
  </div>
      <%= f.hidden_field :published_date, value: Time.now%>
      <%= f.hidden_field :host, value: "socialreader"%>
      <%= f.hidden_field :popular, value: 1%>
  <div class="two fields">
    <div class="field">
      <label>Category</label>
       <%= f.select(:category,Review::CATEGORIES,:multiple => true, class: "ui dropdown")  %>
    </div>
  </div>
  <h4 class="ui dividing header">Content</h4>
  <%= f.cktext_area :content %>
  <div class="field">
    <label>Tag</label>
      <div class="field">
        <%= f.text_field :tag, placeholder: "Divided by ,"%>
      </div>
  </div>
  <%= f.submit "Post", class: "positive ui button"%>
<%end%>

app/views/admin/reviews/show.html.erb
<% provide(:title, "Review")%>
<div class="ui huge breadcrumb">
  <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_reviews_path%>">Reviews</a>
  <i class="right chevron icon divider"></i>
  <div class="active section">Review: <a href="<%=admin_review_path(@review)%>"><%=@review.title[0..20]%>...</a></div>
</div>
<div id="container">
  <h1 class="ui header"><%= @review.title %></h1>
  <div class="ui message page grid">
        <p> Posted at <%= @review.published_date.strftime("%d/%m/%Y")%> @ <%=link_to "#{@review.host}",reviews_path(forum: "#{@review.host}")%>.<br>
        This review has been viewed <%= @review.popular%> times and classified into
        <%= render 'shared/review_category_tag'%>
           category by <%=link_to "SocialReader", root_path%>.<br>
           <% unless @review.host == "socialreader" %>
        You can also view <%= link_to "source review", @review.url%>.</p>
          <% end %>
         <div class="ui form">
            <%= form_for [:admin,TrainReview.new] do |f|%>
          <%= f.hidden_field :_id, value: @review.id%>
            <%= f.select(:category,Review::CATEGORIES, class: "ui dropdown")%>
            <%=f.submit "Add to train data", class: "ui green button"%>
          <%end%>
          </div>
          <div class="ui form">
            <%= form_for [:admin,TestReview.new] do |f|%>
          <%= f.hidden_field :_id, value: @review.id%>
            <%= f.select(:category,Review::CATEGORIES, class: "ui dropdown")%>
            <%=f.submit "Add to test data", class: "ui red button"%>
          <%end%>
          </div>

          <a class="ui primary button" href="<%=new_admin_train_review_path%>">
            New train data
          </a>
</div>
  <p><%=@review.content.html_safe%></p>
  <span class="ui tag label">Tags</span>
  <div class="ui celled horizontal list">
    <% @review.tag.each do |tag|%>
      <div class="item"><%=link_to "#{tag}", reviews_path(:tag=> tag)%></div>
    <% end %>
  </div>


<% if user_signed_in? %>
  <div class="ui comments">
    <h3 class="ui dividing header">Comments (<%=@review.comments.count%>)</h3>
    <%= render @review.comments %>
    <%= form_for([@review, @comment]) do |f|%>
    <div class="ui reply form" style="padding-top:20px">
      <div class="field">
        <%= f.text_area :content%>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
        <%= f.submit "Add reply", class: "ui green button"%>
    </div>
    <% end %>
  </div>
  <%end %>