config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root "static_pages#home"

  resources :reviews do
    resources :comments
  end
  resources :train_texts
  resources :searches
  resources :users
  resources :clipped_reviews, controller: "clipped_reviews"

  namespace :admin do
    root "static_pages#home"
    resources :trains
    resources :train_texts
    resources :train_reviews
    resources :test_reviews
    resources :reviews
    resources :users
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Paperclip

  has_many :reviews, dependent: :destroy
  validates :email, uniqueness: true
  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_mongoid_attached_file :avatar, :style => {:default_url => "images/missing.png"}

  field :name, type: String
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :admin, type: Boolean, default: false
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time
  field :remember_created_at, type: Time
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field :clipped_reviews, type: Array, default: Array.new()

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users=User.all
  end

  def edit
    @user=User.find params[:id]
  end

  def update
    @user=User.find params[:id]
    @user.update_attributes user_params
    redirect_to admin_users_path
    flash[:success]="User has been updated"
  end

  def destroy
    @user=User.find params[:id]
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:name,:admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user=User.find params[:id]
  end

  def edit
    @user=User.find params[:id]
  end

  def update
    @user=User.find params[:id]
    byebug
    @user.update_attributes user_params
    redirect_to users_path
    flash[:success]="User has been updated"
  end

  def destroy
    @user=User.find params[:id]
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:name,:admin)
  end
end

app/views/admin/users/_user.html.erb
<tr>
  <td>
      <div class="content">
        <div class="sub header"><%= user.name %>
      </div>
    </div>
  </td>
  <td>
    <%= user.email %>
  </td>
  <td>
    <%= user.reviews.count %>
  </td>
  <td>
  <% unless current_user == user%>
    <a class="ui green button" href="<%=edit_admin_user_path(user)%>">Edit</a>
    <a class="ui red button" href="<%=admin_user_path(user)%>"  data-method="delete">Delete</a>
  <%else%>
    <a class="ui green button" href="<%=edit_admin_user_path(user)%>">Edit</a>
    <a class="ui disabled red button" href="<%=admin_user_path(user)%>">Delete</a>
  <%end%>
  </td>

</tr>

app/views/admin/users/edit.html.erb
<%provide(:title, "Edit #{@user.name}")%>
<div class="ui three column centered grid">
  <div class="column">
    <h2 class="ui two column centered grid">Edit user: <%=@user.name%></h2>
    <div class="ui form">
    <%= form_for [:admin,@user] do |f|%>

      <div class="field">
        <%= f.label :admin %><br />
       <%= f.select(:admin,[false,true], class: "ui dropdown")  %>
      </div>

       <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "Edit", class: "ui positive button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<%provide(:title,"All users")%>
<div class="ui huge breadcrumb">
  <a class="section" href="<%= admin_root_path %>">Home</a>
  <i class="right chevron icon divider"></i>
  <a class="section" href="<%=admin_users_path%>">Users</a>
</div>
<table class="ui very basic collapsing celled table">
  <thead>
    <tr><th>User</th>
    <th>Email</th>
    <th>Posts</th>
    <th>Actions</th>
  </tr></thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>